name: CI/CD

on:
  push:
    branches: [main]

jobs:
  ruff-linter:
    runs-on: ubuntu-latest
    steps:
      - name: download repo
        uses: actions/checkout@v4

      - name: download python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: download ruff
        run: pip install ruff

      - name: check code quality
        run: ruff check .


#  tests:
#    runs-on: ubuntu-latest
#    steps:
#      - name: download repo
#        uses: actions/checkout@v4
#
#      - name: download python
#        uses: actions/setup-python@v5
#        with:
#          python-version: "3.10"
#          cache: 'pip'
#
#      - name: run tests
#        run:

  deploy:
    runs-on: ubuntu-latest
    steps:
      -